; PlatformIO Project Configuration File
;
; XTouch - 5-inch ESP32-S3 / JC8048W550C_I

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_ldf_mode = deep+

monitor_speed = 115200

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.partition = app3M_fat9M_16MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

lib_deps =
    lovyan03/LovyanGFX@^1.1.12
    lvgl/lvgl@8.3.9
    https://github.com/knolleary/pubsubclient.git
    ArduinoJson@6.21.5
    FS
    SD
    https://github.com/PaulStoffregen/OneWire.git
    https://github.com/milesburton/Arduino-Temperature-Control-Library.git
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/adafruit/DHT-sensor-library.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

build_flags =
    -D__XTOUCH_SCREEN_50__
    -DBOARD_HAS_PSRAM
    -DDEBUG_TOUCH
    -mfix-esp32-psram-cache-issue
    -D LV_CONF_PATH="${PROJECT_DIR}/resources/lv_conf.h"

extra_scripts =
    pre:scripts/pre-build.py
    pre:scripts/version.py
